# Generated by Django 3.0.7 on 2020-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(choices=[(1, 'PAID'), (0, 'UNPAID')], default=0),
        ),
    ]
