# Generated by Django 3.0.6 on 2020-05-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('read_folder', models.CharField(default='', max_length=255)),
                ('write_folder', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates',
                                   to='folders.Folder')),
            ],
            options={
                'db_table': 'template',
            },
        ),
    ]
