# Generated by Django 3.0.6 on 2020-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('metadata', models.CharField(max_length=255)),
                ('recognize_type', models.SmallIntegerField(
                    choices=[(0, 'ENG'), (1, 'VIE'), (2, 'ENG_MULTIPLE_LINE'), (3, 'VIE_MULTIPLE_LINE'), (4, 'DIGIT'),
                             (5, 'CHECKBOX')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bounding_box',
            },
        ),
    ]
