# Generated by Django 3.0.6 on 2020-05-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('templates', '0001_initial'),
        ('bounding_boxes', '0002_boundingbox_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingbox',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bounding_boxes', to='templates.Template'),
        ),
    ]
