# Generated by Django 3.0.7 on 2020-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bounding_boxes', '0004_boundingbox_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingbox',
            name='recognize_type',
            field=models.SmallIntegerField(
                choices=[(0, 'ENG'), (1, 'VIE'), (2, 'ENG_MULTIPLE_LINE'), (3, 'VIE_MULTIPLE_LINE'), (4, 'DIGIT'),
                         (5, 'CHECKBOX'), (6, 'EMAIL')], default=0),
        ),
    ]
