# Generated by Django 3.0.5 on 2020-05-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200426_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
